name: Sync Fork with Upstream

on:
  # 定时触发，例如每天凌晨 0 点 UTC 时间
  schedule:
    - cron: '0 0 * * *'
  # 也可以手动触发
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        # 使用 actions/checkout@v4 来克隆你的仓库
        uses: actions/checkout@v4
        with:
          # 需要获取所有历史记录才能正确合并
          fetch-depth: 0
          # 使用 GITHUB_TOKEN 允许推送更改
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add upstream remote
        # 添加上游仓库作为远程，如果已存在则忽略错误
        run: git remote add upstream https://github.com/LibreSpark/LibreTV.git || true

      - name: Fetch upstream
        # 从上游仓库获取最新更改
        run: git fetch upstream

      - name: Merge upstream into main
        # 切换到你的主分支（请根据你的仓库实际情况修改 main 或 master）
        # 将上游的主分支合并到你的本地主分支
        run: |
          git checkout main # <-- 请确认你的主分支是 main 还是 master
          git merge upstream/main # <-- 请确认上游的主分支是 main 还是 master
        # 如果合并失败（有冲突），Action 会失败，需要手动解决

      - name: Push changes to your fork
        # 将合并后的更改推送到你的 fork
        run: git push origin main # <-- 请确认你的主分支是 main 还是 master
